.gitignore, .vscode, web/.eslintrc.json, web/.vscode/extensions.json, web/.vscode/settings.json, web/src/api/getState.ts, web/src/api/getZone.ts, web/src/api/helpers.ts, web/src/components/__tests__/Fruit.tsx, web/src/main.tsx, web/src/setupTests.ts, web/src/utils.ts
Changes from "all" to "recommended" for all plugins.
Adjusts some rules.
Also added the `.vscode` folder that was gitignored and a symlink so you can open both `web` and `/` in VSCode and still get the same settings.
There's some rules here about larger patterns we should discuss!
1. **Filenames** Keep
`PascalCase` for components, `camelCase` for everything else?
(The is default in the starter, but we can do whatever)
2. **Declaring components** Discuss
It can be done in a bunch of different ways in JS. Should we enforce strictness around this?
Starter uses `react/function-component-definition: [“error”, {“namedComponents”: “function-declaration”}]`which means this:
```js
// incorrect (arrow function)
const CoolComponent = ({name}) => <div>{name}</div>
// correct
function CoolComponent({ …
```
=> Cleans up ESLint rules

web/index.html, web/public/robots.txt
Adbot needs to be specifically named, all other crawlers are covered by *
=> block all crawlers

web/src/main.tsx, web/src/utils/errorOverlay.ts
Ensure more runtime errors are shown in an error modal to make life easier while developing.
=> Adds error overlay to display runtime errors

web/src/features/header/Header.tsx, web/src/features/time/TimeController.tsx
- Makes Header not fixed again and makes TimeController fixed instead.
-  This way we can easily position layout buttons etc, instead of always pushing things down based on header height
- Makes header links big again
- Makes time controller appear on top of panel
=> Fixed layout problems with Header

web/src/api/getFruits.ts, web/src/components/MapButton.tsx, web/src/features/map-controls/MapControls.tsx
Make the div behind the map-controls pass through click events and remove legacy fruits api
=> less fruits, more clickable map

web/src/features/charts/tooltipCalculations.test.ts, web/src/features/charts/tooltipCalculations.ts, web/src/features/charts/tooltips/AreaGraphTooltip.tsx, web/src/features/charts/tooltips/BreakdownChartTooltip.tsx, web/src/features/charts/tooltips/CarbonChartTooltip.tsx, web/src/features/charts/tooltips/EmissionChartTooltip.tsx, web/src/features/charts/tooltips/PriceChartTooltip.tsx, web/vite.config.ts
- Ensures hydro storage correctly shows instead of '?'
- Ensures production that is 0 is shown as 0 instead of '?' and null production is shown as '?'
Also added some tests.
=> BreakdownChartTooltip bugfixes

web/src/features/charts/bar-breakdown/BarBreakdownChart.tsx, web/src/features/panels/LeftPanel.tsx
We had two elements with overflow, which created a lot of extra space.
I also add some padding to the barbreakdownchart as it was slightly misaligned with the areagraphcharts
Before:
Now:
=> 🎁 Provides extra space in zonedetails

web/src/features/time/TimeControllerWrapper.tsx, web/src/features/time/TimeHeader.tsx
I don't think we should use the snapshots to provide extra safe area. It doesn't seem to work on web mobile anyways.
Perhaps this newer version of bottomsheet does it automagically?
Now
=> 🎁 Update bottom sheet snap points

web/src/components/tooltips/utilities.ts, web/src/features/charts/bar-breakdown/BarBreakdownChart.tsx, web/src/features/charts/elements/AreaGraphLayers.tsx, web/src/features/charts/tooltips/AreaGraphTooltip.tsx, web/src/features/map/Map.tsx
Had a lot of issues navigating with the tooltips on mobile, specifically closing and opening tooltips was annoying. I figured it might be good to have a dismiss button alongside the tooltips so users can close it.
In terms of code, in this implementation the button doesn't actually do anything, but magically closes the tooltip because the event is considered a onLeave. That might not work as flawlessly on capacitor?
- Adds some CSS styling to make interactions more intuitive on mobile
- Adds an X button which can be used to close down the tooltip on mobile
=> 🎁 Improve tooltip interactivity on mobile

web/src/features/charts/bar-breakdown/BarBreakdownChart.tsx, web/src/features/charts/bar-breakdown/BarBreakdownEmissionsChart.tsx, web/src/features/charts/bar-breakdown/BarBreakdownProductionChart.tsx, web/src/features/charts/graphUtils.test.ts, web/src/features/charts/graphUtils.ts, web/src/features/charts/tooltipCalculations.test.ts, web/src/features/charts/tooltipCalculations.ts, web/src/features/charts/tooltips/BreakdownChartTooltip.tsx, web/src/features/charts/types.ts, web/src/stories/tooltips/BreakdownChartTooltip.stories.ts, web/src/types.ts
https://linear.app/electricitymaps/issue/ELE-1536/chart-tooltip-breaks-any-aggregate-but-hourly
Fixes the crashing tooltips on non-hourly view. I had a hard time understanding what's going on here, so I added more tests to make sure it (hopefully) still works 😄
=> Fixes tooltip crash

web/src/features/map/Map.tsx, web/src/features/panels/zone/ZoneHeader.tsx
https://linear.app/electricitymaps/issue/ELE-1542/fix-product-consumption-toggle-again
I don't think it was broken, just not implemented. I've added it to the map and the Zone Detail header. Is there anywhere else?
=> allow toggle between production and consumption

web/src/features/charts/ChartTitle.tsx, web/src/features/charts/PriceChart.tsx, web/src/features/panels/zone/Attribution.tsx, web/src/features/panels/zone/NoInformationMessage.tsx, web/src/index.css
https://linear.app/electricitymaps/issue/ELE-1553/add-get-our-data-to-link-above-charts-improve-spacing
Adds a new link with improved spacing as a subtitle to the charts. Also doesn't render the price chart title when there is no price chart.
=> add get our data link

web/src/features/charts/tooltips/BreakdownChartTooltip.tsx
https://linear.app/electricitymaps/issue/ELE-1576/breakdown-chart-tooltip-on-emissions-mode-to-use-correct-value-and
Update the tooltip to show the correct value in emission breakdown mode
=> correct emmsions tooltip

web/public/locales/de.json
https://linear.app/electricitymaps/issue/ELE-1578/new-feature-german-for-time-selector
Adds a German translation for the time selector, this is a google translation and a native German speaker should validate.
@ciril-emaps Do you understand german?
If so, is this an effective translation of "Display data from the past"
=> time controller german translation

web/src/features/charts/elements/AreaGraph.tsx, web/src/features/charts/tooltips/CarbonChartTooltip.tsx
https://linear.app/electricitymaps/issue/ELE-1575/make-chart-tooltips-respect-the-consumption-production-toggle
Carbon breakdown tooltip was not respecting the production / consumption toggle
=> show production / consumption in carbon tooltip

web/src/components/CarbonIntensitySquare.tsx, web/src/features/exchanges/ExchangeTooltip.tsx, web/src/utils/formatting.ts
https://linear.app/electricitymaps/issue/ELE-1557/app-inconsistent-spacing-on-numbers-and-units-throughout-the-app
Improves the spacing to add consistency of spacing between units, gathered some feedback from sciency and designy people in the office :)
=> add spacing for units

web/src/components/CircularGauge.stories.tsx, web/src/components/CircularGauge.tsx, web/src/components/tooltips/TooltipWrapper.tsx, web/src/features/exchanges/ExchangeArrow.tsx, web/src/features/map/MapTooltip.tsx, web/src/features/panels/zone/ZoneHeader.tsx
https://linear.app/electricitymaps/issue/ELE-1558/add-tooltip-to-lowcarbon-gauge
Adds the tooltip. Thought we needed it in other places, so made the gauge support that - but maybe wasn't needed I see now 😬 
I also fixed a bug on the MapTooltip where the number was wrong.
=> Adds tooltip to LowCarbon Gauge in panel

web/src/features/map/Map.tsx
The fly to zone feature could leave zones in a hovered state, this PR unhovers zones that are not the zone being clicked
=> unhover other zones on click

web/public/locales/en.json, web/src/App.tsx, web/src/components/legend/LegendContainer.tsx, web/src/features/charts/tooltipCalculations.ts, web/src/features/charts/tooltips/BreakdownChartTooltip.tsx, web/src/features/map/Map.tsx, web/src/features/map/MapWrapper.tsx
- https://linear.app/electricitymaps/issue/ELE-1623/legend-overlaps-map-controls-on-smaller-screens
- https://linear.app/electricitymaps/issue/ELE-1599/hydro-storage-is-using-hydro-installed-capacity-in-tooltip
- https://linear.app/electricitymaps/issue/ELE-1580/glow-in-the-dark-exchange-arrows-when-using-solar-layer
- https://linear.app/electricitymaps/issue/ELE-1601/country-name-is-not-included-in-exchanges-between-subzones-or-subzone
=> Minor fixes

web/src/components/CarbonIntensitySquare.tsx, web/src/features/map/MapTooltip.tsx, web/src/features/panels/zone/ZoneHeader.tsx
https://github.com/electricitymaps/electricitymaps-contrib/issues/4955
We had hardcoded strings for the gauges and square. This PR fixes that
=> Squares and gauges now uses translations

web/src/features/panels/zone/ZoneDetails.tsx, web/vite.config.ts
This fixes the problem where https://app.electricitymaps.com/zone/hello would crash. We also had to disable the chunks as it broke the build - Radix was trying to use React, but crashed because it didn't have it available (probably because it loaded one before the other?)
=> Fixes /zone/WHATEVZ breaking the app + disables chunking for now

web/src/features/exchanges/ExchangeArrow.tsx
Looks like we where using a div instead of a picture tag which broke our ability to fetch webp images instead, slowing things down a little (the webp images are way smaller!).
=> Change div to picture to fix webp exchange arrows

web/src/features/panels/zone/Attribution.tsx, web/src/features/time/TimeAxis.tsx
https://sentry.io/share/issue/c55c9e1c8c304af2a4b54177132c94f4/
Use old school replace instead of replace all for old browser compatibility
=> stop replace all errors

web/src/main.tsx
I'm not sure we use this and it's an experimental feature + it should only work when NODE_ENV != production.
=> comment out atom dev tools

web/index.html
We where accidentally including a non valid language code that brought down or SEO score.
Fixes the above issue and adds preconnects for sentry and plausible as well as fixing the preconnect to the backend that still use our old domain (electricitymaps.org).
PS: I also moved the main bundle script tag to where vite puts it after build, makes the file a little easier to understand.
=> Fix invalid href lang + add preconnects
