- mobileapp/package.json
> capacitor scripts

- web/.eslintrc.json
- web/package.json
- web/pnpm-lock.yaml
The class name sorting is nice. I had a look through other tools and add ins for Tailwind but I think we've got it covered. If we need more later we can pull them in.
> add tailwind classname package

- web/package.json
- web/pnpm-lock.yaml
- web/src/features/header/Header.tsx
> Tonyvanswet/ele 1338 UI header component

- web/src/components/TimeAverageToggle.tsx
- web/src/components/TimeSlider.tsx
- web/src/features/panels/LeftPanel.tsx
- web/src/features/time/TimeAxis.tsx
- web/src/features/time/TimeController.tsx
- web/src/utils/formatting.ts
- web/src/utils/helpers.ts
- web/src/utils/viewport.ts
- web/tailwind.config.js
https://linear.app/electricitymaps/issue/ELE-1356/[ui]-timeslider-component
Can be reviewed per commit.
Adds  the timecontroller as we know and love with a few changes from Rasmus' updated visuals. 
Some things to think about
- Should we manage datetimes as strings or dates? We want to use strings for indexing directly
- I don't think selectedDatetimeIndex is clear. I constantly think it's a number even though it's a string so i am thinking of changing the atom name cc @tonypls wdyt?
- I've not added much performance improvements here. We could do some memorizing and stuff. Here we also run into a bit of pain in terms not having the datetimeindex anymore as we have to run through the datetime list to get the index -.-
> Timeslider

- web/README.md
- web/index.html
- web/package.json
- web/pnpm-lock.yaml
- web/src/components/TimeAverageToggle.tsx
- web/src/features/panels/LeftPanel.tsx
- Set up react-icons
- document usage in web/README.md
- Add real icons for panel-collapse-button and clock
- (unrelated) fixes html lang that was changed
Closes https://linear.app/electricitymaps/issue/ELE-1377/set-up-process-for-icons
> Set up icons and replaces existing usage

- web/package.json
- web/pnpm-lock.yaml
- web/src/components/Flag.tsx
- web/src/features/panels/zone/CountryTag.tsx
I'm changing usage and fixing the zone header with actual data in a separate PR!
> Adds new Flag component

- web/src/components/TimeAverageToggle.tsx
- web/src/components/ToggleButton.tsx
- web/src/features/time/TimeAxis.tsx
- web/src/features/time/TimeController.tsx
https://linear.app/electricitymaps/issue/ELE-1480/make-all-relevant-things-non-selectable
Make items users interact with not user selectable
> no user select for buttons / controllers

- web/src/components/tooltips/MapTooltip.tsx
- web/src/features/charts/bar-breakdown/BarBreakdownChart.tsx
- web/src/features/charts/bar-breakdown/BarBreakdownProductionChart.tsx
- web/src/features/charts/hooks/useBarBreakdownProductionChartData.ts
Follow-up to https://github.com/electricitymaps/electricitymaps-contrib-rewrite/pull/64#discussion_r1039515189
Also reverts changes related to https://github.com/electricitymaps/electricitymaps-contrib-rewrite/pull/65#discussion_r1040932817 as I missed how the full data is used:
> Fixes tooltip issue + broken bar breakdown chart

- web/package.json
- web/pnpm-lock.yaml
- web/src/App.tsx
- web/src/features/time/TimeController.tsx
- web/src/features/time/TimeControllerWrapper.tsx
- web/src/features/time/TimeHeader.tsx
- web/src/index.css
- web/src/main.tsx
- web/src/utils/polyfills.ts
- web/src/utils/styling.ts
https://linear.app/electricitymaps/issue/ELE-1509/styling-tweaks-for-mobile-web
Makes the TimeController fit inside a sheet.
> Makes TimeController nice on small screens

- web/package.json
- web/pnpm-lock.yaml
- web/src/App.tsx
- web/src/components/TimeAverageToggle.tsx
- web/src/features/header/Header.tsx
- web/src/features/map-controls/MapControls.tsx
- web/src/features/map-controls/ZoomControls.tsx
- web/src/features/map/Map.tsx
- web/src/features/panels/LeftPanel.tsx
- web/src/features/panels/zone/ZoneDetails.tsx
- web/src/features/panels/zone/ZoneHeaderTitle.tsx
- web/src/features/time/TimeController.tsx
- web/src/features/time/TimeControllerWrapper.tsx
- web/src/features/time/TimeHeader.tsx
- web/src/index.css
- web/src/main.tsx
- web/src/utils/helpers.ts
- web/src/utils/polyfills.ts
- web/src/utils/styling.ts
https://linear.app/electricitymaps/issue/ELE-1509/styling-tweaks-for-mobile-web
A bunch of smaller tweaks for responsive and especially small/mobile-sized screens.
> Small screen tweaks

- web/src/features/map-controls/MapControls.tsx
- web/src/features/panels/ranking-panel/InfoText.tsx
- web/src/features/panels/ranking-panel/RankingPanel.tsx
- web/src/features/panels/ranking-panel/SocialButtons.tsx
- web/src/features/panels/ranking-panel/ZoneList.tsx
https://linear.app/electricitymaps/issue/ELE-1458/finalise-ranking-panel-style
This adds the info text and "social media" buttons. 
Also makes height of the zone-list flexible.
With this, the Ranking Panel should be feature- and styling complete! 🥳
> Finalise Ranking Panel

- web/package.json
- web/pnpm-lock.yaml
- web/src/components/tooltips/utilities.ts
- web/src/features/charts/elements/AreaGraph.tsx
- web/src/features/charts/tooltips/AreaGraphTooltip.tsx
- web/src/features/charts/tooltips/BreakdownChartTooltip.tsx
- web/src/features/charts/tooltips/CarbonChartTooltip.tsx
- web/src/features/charts/tooltips/EmissionChartTooltip.tsx
- web/src/features/charts/tooltips/PriceChartTooltip.tsx
- web/src/main.tsx
Works similar to the production app.
> Set up mobile tooltips

- web/src/components/MapButton.tsx
- web/src/features/map-controls/MapControls.tsx
- web/src/features/weather-layers/wind-layer/WindLayer.tsx
- web/src/utils/state/atoms.ts
Since loading weather data and layers can take some time, it's hard to know as a user that something is happening. This should help solve that :) The buttons also had so much similar logic that I decided to abstract it - dunno if worth it, but now it's done ¯\\\_(ツ)\_/¯
> Adds loading indicators on weather buttons

- web/src/components/LoadingOverlay.tsx
- web/src/components/ToggleButton.tsx
- web/src/features/panels/zone/CountryTag.tsx
- web/src/features/panels/zone/DisplayByEmissionToggle.tsx
- web/src/features/panels/zone/ZoneHeaderTitle.tsx
Some updates of the left panel to prevent overflow in the toggle buttons and remove duplicate flags for subzones
> tidy left panel

- web/src/features/map-controls/MapButton.tsx
- web/src/features/map-controls/MapControls.tsx
- web/src/features/panels/ranking-panel/SocialButtons.tsx
- web/src/hooks/oldThemes.ts
- web/src/hooks/theme.ts
- web/src/utils/state/atomWithCustomStorage.ts
- web/src/utils/state/atoms.ts
https://linear.app/electricitymaps/issue/ELE-1384/set-up-colorblind-mode-that-changes-co2-scale
Adds colorblind-mode. Used a button along with the other map controls instead of the checkbox in ranking panel.
https://user-images.githubusercontent.com/3296643/208942738-f6317113-e3bb-4215-93f2-33217652c4b8.mov
> Adds colorblind-mode

- web/src/features/map/map-utils/generateTopos.ts
> 🎁  Excludes subzone geometries on useGetGeometries

- web/src/features/panels/zone/ZoneDetails.tsx
> 🎁  Style loading spinner in dark mode

- web/src/features/map-controls/MapControls.tsx
Not sure if the current approach was missing some new translations or something like that. I've just reused the current ones now.
> 🎁 Add tooltip text for weather buttons

- web/src/features/charts/bar-breakdown/EmptyBarBreakdownChart.tsx
> 🎁 Add dark mode bg for overlay

- web/src/components/legend/Co2Legend.tsx
- web/src/components/legend/ColorBar.tsx
- web/src/components/legend/LegendContainer.tsx
- web/src/components/legend/SolarLegend.tsx
- web/src/components/legend/WindLegend.tsx
- web/src/components/legend/solarScale.ts
- web/src/hooks/colors.ts
- web/src/hooks/theme.ts
- web/src/stories/charts/BreakdownChart.stories.ts
https://linear.app/electricitymaps/issue/ELE-1523/add-wind-and-solar-legends
Added solar and wind legends!! Also renamed "oldThemes" to colors as it more succinctly  explains what it does and removes confusion from other themes files.
> solar and wind legends

- web/src/components/Badge.tsx
- web/src/features/panels/zone/ZoneDetails.tsx
- web/src/features/panels/zone/ZoneHeaderTitle.tsx
> 🎁 Display estimated and aggregated badges

- web/src/features/header/Header.tsx
- web/src/features/map-controls/MapControls.tsx
- web/src/features/panels/zone/DisplayByEmissionToggle.tsx
- web/src/features/time/TimeController.tsx
- web/src/utils/analytics.ts
I didn't add the modal events
https://linear.app/electricitymaps/issue/ELE-1354/set-up-plausible-analytics
> Adds custom plausible events

- web/src/components/modals/OnboardingModal.tsx
- web/src/components/modals/OnboardingModalInner.tsx
- web/src/features/map-controls/MapControls.tsx
- web/src/features/time/TimeControllerWrapper.tsx
https://linear.app/electricitymaps/issue/ELE-1527/mobile-onboarding-modal
The onboarding modal has been updated to be more responsive.
> onboarding modal for mobile

- web/package.json
- web/public/client-version.json
- web/scripts/deploy.sh
Fixes issue where you cannot refresh the page (as it is on `/map`) by setting a "fallback"/error file to be the index file.
Also changes the deploy scripts to ensure versions are updated in correct order.
https://beta.electricitymaps.com/map
> Fix broken refresh on app

- web/package.json
- web/pnpm-lock.yaml
- web/src/utils/analytics.ts
- web/src/utils/createConsoleGreeting.ts
Currently it crashes because adblockers block the Plausible script. This fixes it :)
I also bumped react-icons to get this fix: https://github.com/react-icons/react-icons/pull/630
> Fixes issue when adblocker is used + adds types

- web/src/features/map/Map.tsx
Center on caller location and fly to zone when clicked
> fly to places

- web/src/features/charts/tooltips/BreakdownChartTooltip.tsx
Some more feedback from Rasmus
> capitalize tooltip

- web/src/features/header/Header.tsx
https://linear.app/electricitymaps/issue/ELE-1569/fix-link-on-were-hiring-button
> fix jobs link

- web/src/features/charts/hooks/useBreakdownChartData.ts
https://linear.app/electricitymaps/issue/ELE-1573/graph-show-import-from-both-aggregated-country-and-subzone
The origin of electricity was double counting exchange data from a zone and country level
> filter breakdown chart exchanges for selected aggregate

- web/src/App.tsx
- web/src/features/error-boundary/ErrorBoundary.tsx
Error message was empty after switching to Sentry's error boundary. Fixed it and changed the fallback component from class to function now that it doesn't handle any logic :)
> Updates error boundary message

- web/package.json
- web/public/client-version.json
- web/scripts/generate-index-files.ts
This should fix the problem of us seeing a bunch of 404s impacting SEO :)
Also bumps version numbers to match what Sentry think we're at!
> Generates index files for all paths!

- web/src/features/charts/hooks/useBreakdownChartData.ts
New change cause the app to crash if opening directly to a zone via url
> check for zonedata before getting exchanges

- web/src/components/CarbonIntensitySquare.tsx
- web/src/components/CircularGauge.tsx
- web/src/components/ZoneName.tsx
- web/src/components/modals/OnboardingModal.tsx
- web/src/components/tooltips/TooltipWrapper.tsx
- web/src/features/charts/ChartTitle.tsx
- web/src/features/charts/bar-breakdown/BySource.tsx
- web/src/features/exchanges/ExchangeArrow.tsx
- web/src/features/exchanges/ExchangeTooltip.tsx
- web/src/features/map/MapTooltip.tsx
- web/src/features/panels/zone/ZoneDetails.tsx
- web/src/features/time/TimeControllerWrapper.tsx
Feedback and updates made from pair programming session with Rasmus.
The main focus is to bring consistency to the padding and font sizes / weights across the tooltips and headers.
> Tvs rj/ux peerprogramming

- web/.npmrc
- web/package.json
- web/public/client-version.json
- web/scripts/deploy.sh
- web/src/features/modals/InfoModal.tsx
- web/src/features/panels/LeftPanel.tsx
- web/vite.config.ts
- Ensures pre and post scripts are working  
- Changes Sentry plugin to only upload sourcemaps if token is given
- Disables caching on index files  
- Adds route that removes index.html from url
https://beta.electricitymaps.com/map/index.html
> Deployment improvements

- web/src/features/map/MapTooltip.tsx
- web/src/features/panels/zone/ZoneHeader.tsx
The zone header was showing unknown value for low carbon when it should show 100%
> fix fully renewable header

- web/src/components/CircularGauge.tsx
- web/src/components/ToggleButton.tsx
- web/src/features/charts/BreakdownChart.tsx
- web/src/features/charts/elements/AreaGraph.tsx
- web/src/features/charts/tooltips/AreaGraphTooltip.tsx
- web/src/features/charts/tooltips/BreakdownChartTooltip.tsx
- web/src/features/charts/tooltips/CarbonChartTooltip.tsx
- web/src/features/charts/tooltips/EmissionChartTooltip.tsx
- web/src/features/charts/tooltips/PriceChartTooltip.tsx
- web/src/features/charts/types.ts
- web/src/features/panels/zone/ZoneDetails.tsx
- web/src/features/panels/zone/ZoneHeader.tsx
- web/src/features/time/TimeAxis.tsx
Decided to batch these bug fixes into one PR instead of a lot - but I have carefully split commits into addressing different bugs, so you can review by commit to make it more clear what's happening :)
For the visual changes, I created this quick overview:
> Fixes multiple bugs

- web/src/components/CarbonIntensitySquare.stories.ts
- web/src/components/CarbonIntensitySquare.tsx
- web/src/features/map/MapTooltip.tsx
- web/src/features/panels/zone/ZoneHeader.tsx
https://linear.app/electricitymaps/issue/ELE-1632/disable-fancy-number-animations
We're listening to the feedback and will disable the animating numbers in CO2 squares :)
> Disables transition of numbers
